
- name: Ensure certain required variables are defined
  assert:
    that: "{{ item }} is defined"
  loop:
  - ansible_source_directory
  - collection_destination
  - collection_name
  - collection_organization

- name: "Create the collection directory structure"
  file:
    path: "{{ collection_destination }}/{{ item }}"
    state: directory
  with_items: "{{ directories['collection'] }}"
